// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ysfocNx2Gq8cblXoaH-7jpFcHkC3q5I',
    appId: '1:918827884307:android:a990025977d7575d0c44e6',
    messagingSenderId: '918827884307',
    projectId: 'shopex-130e8',
    storageBucket: 'shopex-130e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkra2OIud-KBxTSslQIjiOeOTPPIgUdK0',
    appId: '1:918827884307:ios:587cf894ad2b7cc30c44e6',
    messagingSenderId: '918827884307',
    projectId: 'shopex-130e8',
    storageBucket: 'shopex-130e8.firebasestorage.app',
    androidClientId: '918827884307-e1div3p8t2mcprlr8biv021n66otqhtj.apps.googleusercontent.com',
    iosClientId: '918827884307-9bfui3hqa737qd8tu13pfm124opaci57.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashbourdFrutsHub',
  );
}
